<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * User_EpisodeRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class User_EpisodeRepository extends EntityRepository
{
    public function findByUser($userId)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e FROM AppBundle:User_Episode e WHERE e.user_id = :id'
            )
            ->setParameter('id', $userId)
            ->getResult();
    }
}
