<?php

namespace AppBundle\Repository;

/**
 * User_EpisodeRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class User_EpisodeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUser($userId)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e FROM AppBundle:User_Episode e WHERE e.user_id = :id'
            )
            ->setParameter('id', $userId)
            ->getResult();
    }

    public function findByUserEpisode($uid,$eid){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e FROM AppBundle:User_Episode e WHERE e.user_id = :uid AND e.episode_id = :eid'
            )
            ->setParameter('uid', $uid)
            ->setParameter('eid',$eid)
            ->getResult();
    }
}
